xmrbackers/routes/creator.py
from quart import Blueprint, render_template, flash, redirect, url_for
from flask_login import current_user, login_required
from monero.wallet import Wallet

from xmrbackers.forms import ConfirmSubscription
from xmrbackers.models import User, CreatorProfile, BackerProfile, TextPost
from xmrbackers.models import Subscription, SubscriptionMeta
from xmrbackers.helpers import check_tx_key
from xmrbackers import config


bp = Blueprint('creator', 'creator')

@bp.route('/creators')
async def all():
    creators = CreatorProfile.select().order_by(
        CreatorProfile.create_date.desc()
    )
    return await render_template('creator/creators.html', creators=creators)

@bp.route('/creator/<username>')
async def show(username):
    user = User.select().where(User.username == username)
    creator = CreatorProfile.select().where(
        CreatorProfile.user == user
    ).first()
    if creator:
        posts = TextPost.select().where(
            TextPost.creator == creator,
            TextPost.hidden == False
        ).order_by(TextPost.post_date.desc())
        return await render_template(
            'creator/creator.html',
            creator=creator,
            posts=posts
        )
    else:
        await flash('That creator does not exist.')
        return redirect(url_for('meta.index'))

@bp.route('/creator/<username>/subscription')
async def subscription(username):
    user = User.select().where(User.username == username)
    creator = CreatorProfile.select().where(
        CreatorProfile.user == user
    )
    if creator:
        subscription_meta = SubscriptionMeta.select().where(
            SubscriptionMeta.creator == creator
        ).order_by(SubscriptionMeta.create_date.desc()).first()
        form = ConfirmSubscription()
        return await render_template(
            'creator/subscription.html',
            subscription_meta=subscription_meta,
            form=form
        )
    else:
        await flash('That creator does not exist.')
        return redirect(url_for('meta.index'))

@bp.route('/subscription/<int:subscription_id>/confirm', methods=['POST'])
async def confirm_subscription(subscription_id):
    # do checks here for SubscriptionMeta assumption
    sm = SubscriptionMeta.get_or_none(subscription_id)
    form = ConfirmSubscription()
    if form.validate_on_submit():
        w = Wallet(
            port=8000,
            user=config.XMR_WALLET_RPC_USER,
            password=config.XMR_WALLET_RPC_PASS
        )
        check_data = {
            'txid': form.tx_id.data,
            'tx_key': form.tx_key.data,
            'address': form.wallet_address.data
        }
        try:
            res = w._backend.raw_request('check_tx_key', check_data)
        except:
            await flash(f'Invalid transaction! No subscription for you!')
            return redirect(url_for('creator.show', username=sm.creator.user.username))

        if res['received'] >= sm.atomic_xmr:
            backer_profile = BackerProfile.select().where(
                BackerProfile.user == current_user
            ).first()
            s = Subscription(
                creator=sm.creator.id,
                backer=backer_profile.id,
                meta=sm.id,
            )
            s.save()
            await flash(f'Found valid transaction! You are now subscribed to {sm.creator.user.username}!')
            return redirect(url_for('creator.show', username=sm.creator.user.username))
        else:
            await flash('Not enough XMR sent! No subscription for you!')
            return redirect(url_for('creator.show', username=sm.creator.user.username))
    else:
        await flash('Unable to accept form POST.')
        return redirect(url_for('meta.index'))

xmrbackers/routes/post.py
from quart import Blueprint, render_template, flash, redirect, url_for
from flask_login import current_user

from xmrbackers.models import TextPost, Subscription


bp = Blueprint('post', 'post')

@bp.route('/post/<int:post_id>')
async def show(post_id):
    post = TextPost.get_or_none(post_id)
    if post:
        if current_user.is_anonymous:
            await flash('You must login to view this post.')
            return redirect(url_for('creator.show', username=post.creator.user.username))
        user_subscriptions = Subscription.select().where(
            Subscription.active == True,
            Subscription.backer == current_user.backer_profile.first()
        )
        if user_subscriptions:
            return await render_template('post/show.html', post=post)
        else:
            await flash('Viewing posts requires a subscription.')
            return redirect(url_for('creator.subscription', username=post.creator.user.username))
    else:
        flash('That post does not exist.')
        return redirect(url_for('meta.index'))

xmrbackers/templates/creator/creator.html
<!DOCTYPE HTML>
<html>

	{% include 'includes/head.html' %}

	<body class="is-preload landing">
		<div id="page-wrapper">

				{% include 'includes/header.html' %}

				{% if creator %}
          <h1>{{ creator.user.username }}</h1>
          <p>Bio: {{ creator.bio }}</p>
				{% endif %}

				{% if posts %}
					<h1>Posts</h1>
					{% for post in posts %}
						<p><a href="{{ url_for('post.show', post_id=post.id) }}">{{ post.id }} - {{ post.title }} - {{ post.post_date | humanize }}</a></p>
					{% endfor %}
				{% endif %}

				{% include 'includes/footer.html' %}

		</div>

		{% include 'includes/scripts.html' %}

	</body>
</html>

xmrbackers/templates/creator/creators.html
<!DOCTYPE HTML>
<html>

	{% include 'includes/head.html' %}

	<body class="is-preload landing">
		<div id="page-wrapper">

				{% include 'includes/header.html' %}

				{% if creators %}
          <h1>All Creators</h1>
          <ul>
					{% for c in creators %}
						<li><a href="{{ url_for('creator.show', username=c.user.username) }}">{{ c.user.username }}</a> - profile created {{ c.create_date | humanize }}</li>
					{% endfor %}
          </ul>
				{% endif %}

				{% include 'includes/footer.html' %}

		</div>

		{% include 'includes/scripts.html' %}

	</body>
</html>

xmrbackers/templates/creator/subscription.html
<!DOCTYPE HTML>
<html>

	{% include 'includes/head.html' %}

	<body class="is-preload landing">
		<div id="page-wrapper">

				{% include 'includes/header.html' %}

				{% if subscription_meta %}
				<h1>Subscribe</h1>
				<p>Creator: <a href="{{ url_for('creator.show', username=subscription_meta.creator.user.username) }}">{{ subscription_meta.creator.user.username }}</a></p>
				<p>ID: {{ subscription_meta.id }}</p>
				<p>XMR: {{ subscription_meta.atomic_xmr | from_atomic }}</p>
				<p>Address: {{ subscription_meta.wallet_address }}</p>
				<p>Hours: {{ subscription_meta.number_hours }}</p>
				<form method="POST" action="{{ url_for('creator.confirm_subscription', subscription_id=subscription_meta.creator.id) }}">
						{% for f in form %}
							{% if f.name == 'csrf_token' %}
								{{ f }}
							{% else %}
								<div class="form-group">
									{{ f.label }}
									{{ f }}
								</div>
							{% endif %}
						{% endfor %}
						<ul>
						{% for field, errors in form.errors.items() %}
								<li>{{ form[field].label }}: {{ ', '.join(errors) }}</li>
						{% endfor %}
					</ul>
						<input type="submit" value="Confirm" class="btn btn-link btn-outline btn-xl">
				</form>
				{% endif %}

				{% include 'includes/footer.html' %}

		</div>

		{% include 'includes/scripts.html' %}

	</body>
</html>